"""alterar_coluna_icd_code_de_medical_records

Revision ID: 8ee725de439a
Revises: aeeb917bc1ff
Create Date: 2026-01-02 16:58:34.422696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ee725de439a'
down_revision: Union[str, Sequence[str], None] = 'aeeb917bc1ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_records', sa.Column('cid_code', sa.String(length=10), nullable=True))
    op.drop_column('medical_records', 'icd_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_records', sa.Column('icd_code', sa.VARCHAR(length=10), nullable=True))
    op.drop_column('medical_records', 'cid_code')
    # ### end Alembic commands ###
